apps/ImportApp-development/config/routes.rb
Rails.application.routes.draw do

  root 'companies#index'
  resources :companies do
    member do
      get 'operations_search'
    end
  end
  match 'download_csv/:company_id/:query' => 'companies#download_csv', via: :get, as: :download_csv
  match 'operations/upload' => 'companies#upload', via: :post
  match 'fetch_parsing_logs' => 'companies#fetch_parsing_logs', via: :get
  mount Resque::Server, :at => "/resque"

end

apps/ImportApp-development/app/models/company.rb
class Company < ActiveRecord::Base

  has_many :operations
  paginates_per 10

  validates_presence_of :name
  default_scope { includes(:operations) }

  include Statistics
end

apps/ImportApp-development/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.page(params[:page])
    @log = ParsingLog.running_parser

    render partial: "companies_list" if request.xhr?  
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    render partial: "company_details" if request.xhr? 
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /companies/upload
  # File upload from companies index
  def upload
    if valid_data? 
      @log = ParsingLog.new
      @log.operation_file = upload_params
      @log.save
      
      Resque.enqueue(UploadParser, @log.id)
      render text: "Upload Successful"
    end
  end

  #Function to fetch parsing logs
  def fetch_parsing_logs
    @log = ParsingLog.running_parser
    render partial: "parsing_log"
  end

  #Function to search operations
  def operations_search
    query = params[:query]
    company_id = params[:id]
    @operations = Operation.search_data(query, company_id)

    render partial: "operations_search"
  end

  #Function to download CSV
  def download_csv
    query = params[:query]
    company_id = params[:company_id]
    file = Operation.create_csv(query, company_id)  
    send_file file
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params[:company]
    end

    #Function to permit upload params
    def upload_params
      params.require(:upload_file)
    end

    #Funtion to check if valid data
    def valid_data?
      not_blank = (params[:upload_file] != "")
      is_csv = (params[:upload_file].content_type == "text/csv")

      not_blank && is_csv
    end
end

apps/ImportApp-development/app/helpers/companies_helper.rb
module CompaniesHelper

  #Function to render collapse class
  def collapse_class(index)
  	index == 0 ? "collapse in" : "collapse"
  end

  #Funciton to show and hide log
  def show_hide_log(log)
  	log.blank? ? "display: none;" : ""
  end

  #Function to show succeded rows
  def suceeded_rows(log)
  	log ? log.total_rows_suceeded : 0
  end

  #Function to show failed rows
  def failed_rows(log)
  	log ? log.total_rows_failed : 0
  end

  #Function to show total rows
  def total_rows(log)
  	log ? log.total_rows_parsed : 0
  end
end

apps/ImportApp-development/app/views/companies/_companies_list.html.slim
table.table.table-striped style=("border: 1;") 
  thead
    tr
      th Company Id
      th Company Name
      th Action
  tbody
    - @companies.each do |company|
      = render "company_row_single", company: company
      tr id="company_info#{company.id}" 
= paginate @companies

apps/ImportApp-development/app/views/companies/_company_details.html.slim
table.table.table-striped
  tbody
    tr= render "statistics", company: @company
    tr= render "operations", company: @company

apps/ImportApp-development/app/views/companies/_company_row_single.html.slim
tr
  td= "Company ##{company.id} "
  td
    strong= company.name
  td
    strong
      a.company_info_show data-company-id="#{company.id}" href="#"  view operations

apps/ImportApp-development/app/views/companies/_form.html.slim
= form_for @company, :html => { :class => "form-horizontal company" } do |f|
  - if @company.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        h3.panel-title
          = pluralize(@company.errors.count, "error")
          | prohibited this company from being saved:
      .panel-body
        ul
          - @company.errors.full_messages.each do |msg|
            li= msg
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
    = error_span(@company[:name])
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), \
    companies_path, :class => 'btn btn-default'                  \

apps/ImportApp-development/app/views/companies/_operation_search_area.html.slim
div class="form-group"

  input name="filter_text" required="" type="text" placeholder="Type to filter by status, kind, invoice_num and reporter" class="form-control ops-search" data-company-id="#{company.id}"

apps/ImportApp-development/app/views/companies/_operations.html.slim
.row
  .col-md-4
    h2
      strong Operations
  .col-md-8.padddown20
    = link_to "Download as CSV", download_csv_path(company.id, query="*"), :id => "download_csv#{company.id}", :class => "btn btn-primary pull-right"


tr= render "operation_search_area", company: company
table.table.table-striped
  thead
    tr
      th Invoice Id
      th Invoice Number
      th Invoice Date
      th Reporter
  tbody id="operations_body"
    - company.operations.each do |operation|
      tr
        td= "##{operation.id} "
        td= operation.invoice_num
        td= operation.invoice_date
        td= operation.reporter

apps/ImportApp-development/app/views/companies/_operations_search.html.slim
- @operations.each do |operation|
  tr
    td= "##{operation.id} "
    td= operation.invoice_num
    td= operation.invoice_date
    td= operation.reporter

apps/ImportApp-development/app/views/companies/_parsing_log.html.slim
h1 Parsing Log
table.table.table-striped id="parsing_area" 
  thead
    tr
      th Parsing Log Id
      th Started At
      th Total Rows Suceeded
      th Total Rows Fails
      th Total Rows Parsed
      th Status
  tbody
    - @log.each do |log|
      tr
        td= "##{log.id} "
        td= log.created_at
        td id="success_rows#{log.id}" 
          = suceeded_rows(log)
        td id="failed_rows#{log.id}"
          = failed_rows(log)
        td id="total_rows#{log.id}"
          = total_rows(log)
        td id="status#{log.id}"
          = log.status

apps/ImportApp-development/app/views/companies/_statistics.html.slim
.row
  .col-md-4
    h2
      strong Statistics 
  .col-md-8.padddown20
    = link_to "Hide/Show", "#", :class => "btn btn-primary pull-right hide_stats"
 

table.table.table-striped id="stats_table"
  thead
    tr
      th Operation Count
      th Avg. Amout of Ops
      th Highest Optn
      th Accepted operations
  tbody
    tr
      td= company.operation_count
      td= number_to_currency(company.average_amount_operations, precision: 2)
      td= company.highest_operation_this_month
      td= company.accepted_operations_count

hr

apps/ImportApp-development/app/views/companies/_upload_widget.html.slim
form#upload_form action="operations/upload" enctype="multipart/form-data" method="post" multipart="true" 
  input#upload_file_name name="upload_file" required="" type="file" /
  br/
  input.btn.btn-success type="submit" value=("Upload File to Server") /
br/
#upload_area style="display:none;" 
  p.upload_text Upload Progress ....
  .progress
    .bar
    .percent 0%
  #status

apps/ImportApp-development/app/views/companies/edit.html.slim
- model_class = Company
.page-header
  h1= t '.title', :default => [:'helpers.titles.edit', 'Edit % model '], :model => model_class.model_name.human.titleize
= render :partial => 'form'

apps/ImportApp-development/app/views/companies/index.html.slim
- model_class = Company
.page-header
  h1 Companies Dashboard
  = link_to "Upload Operations", "#", class: "btn btn-info upload_btn padd20" 

  = link_to "Show / Hide Parsing Log", "#", class: "btn btn-info parse_btn"
  div id="upload_widget" style="display: none;"
    = render "upload_widget"

div id="parsing_area" style="#{show_hide_log(@log)}"
  = render "parsing_log"
hr

h1 Company List
#companies_list
  .row
    p
      | Loading Companies.... #{image_tag "loader.gif"}
= hidden_field_tag "current_page", params[:page] || 1

apps/ImportApp-development/app/views/companies/new.html.slim
- model_class = Company
.page-header
  h1= t '.title', :default => [:'helpers.titles.new', 'New % model '], :model => model_class.model_name.human.titleize
= render :partial => 'form'

apps/ImportApp-development/app/views/companies/show.html.slim
- model_class = Company
.page-header
  h1= t '.title', :default => model_class.model_name.human.titleize
dl.dl-horizontal
  dt
    strong
      = model_class.human_attribute_name(:name)
      | \:
  dd= @company.name
= link_to t('.back', :default => t("helpers.links.back")), \
  companies_path, :class => 'btn btn-default'              \
= link_to t('.edit', :default => t("helpers.links.edit")), \
  edit_company_path(@company), :class => 'btn btn-default' \
= link_to t('.destroy', :default => t("helpers.links.destroy")),                                               \
  company_path(@company),                                                                                      \
  method => 'delete',                                                                                         |:
  data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |:
  class => 'btn btn-danger'                                                                                   |: